import { useRef, useState } from "react";
interface ResumeAnalysisProps {
  onLogin: () => void;
  onDashboard: () => void;
} 
export default function ResumeAnalysis({
  onLogin,
  onDashboard,  
}: ResumeAnalysisProps) { 
   const [fileName, setFileName] = useState("");
   const [analyzed, setAnalyzed] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [showPopup, setShowPopup] = useState(false);
  const [showSignup, setShowSignup] = useState(false);

  
  return (
    

    <section className="min-h-screen bg-[#F8F6E8] px-6 py-16">
      <div className="max-w-7xl mx-auto">

  <div className="mb-12">
  <h2 className="text-4xl font-bold text-[#171C4A]">
    Resume & GitHub Analysis
  </h2>
  <p className="mt-3 text-gray-500 text-lg">
    Upload your resume or connect GitHub to discover
    skill gaps, strengths, and personalized learning recommendations.
  </p>
</div>

        {/* Main Grid */}
        <div className="grid lg:grid-cols-2 gap-10 mt-16">

          {/* Left Panel */}
          <div className="bg-white rounded-[32px] shadow-xl p-8">

            <h2 className="text-3xl font-bold text-[#171C4A]">
              Analyze Your Profile
            </h2>

            <p className="text-gray-500 mt-2">
              Choose one of the options below
            </p>

           {/* Resume Upload */}
<div className="mt-8 border-2 border-dashed border-gray-300 rounded-3xl p-10 text-center">

  <input
    type="file"
    accept=".pdf,.doc,.docx"
    ref={fileInputRef}
    className="hidden"
    onChange={(e) => {
      const file = e.target.files?.[0];
      if (file) {
        setFileName(file.name);
      }
    }}
  />

  <div className="text-6xl">📄</div>

  <h3 className="mt-4 text-2xl font-bold">
    Upload Resume
  </h3>

  <p className="text-gray-500 mt-2">
    PDF or DOCX • Max 10 MB
  </p>

  <button
    onClick={() => fileInputRef.current?.click()}
    className="mt-6 px-8 py-4 rounded-full bg-[#171C4A] text-white font-semibold hover:opacity-90"
  >
    Choose File
  </button>

  {fileName && (
    <div className="mt-4 bg-green-50 border border-green-200 rounded-xl p-3">
      <p className="text-green-700 font-medium">
        ✓ {fileName}
      </p>
    </div>
  )}
</div>
            {/* Divider */}
            <div className="flex items-center my-8">
              <div className="flex-1 h-px bg-gray-300"></div>
              <span className="px-4 text-gray-400">OR</span>
              <div className="flex-1 h-px bg-gray-300"></div>
            </div>

            {/* GitHub */}
            <div className="border rounded-3xl p-8 flex items-center justify-between">

              <div>
                <h3 className="text-xl font-bold">
                  Connect GitHub
                </h3>

                <p className="text-gray-500">
                  Analyze repositories and coding skills
                </p>
              </div>

              <button className="px-6 py-3 rounded-full bg-black text-white">
                Connect
              </button>
            </div>

            {/* Analyze Button */}
           <button
  disabled={!fileName}
   onClick={() => {
  setAnalyzed(true);

  setTimeout(() => {
    setShowPopup(true);
  }, 1500);
}} 

  className={`w-full mt-8 py-5 rounded-2xl text-lg font-bold transition ${
    fileName
      ? "bg-yellow-300 text-[#171C4A] hover:opacity-90"
      : "bg-gray-300 text-gray-500 cursor-not-allowed"
  }`}
>
  Analyze My Profile →
</button>
          </div>

          {/* Right Panel */}
          <div className="bg-[#171C4A] rounded-[40px] p-8 text-white shadow-2xl">

           <h2 className="text-3xl font-bold">
  {analyzed ? "Analysis Results" : "AI Analysis Preview"}
</h2>

<p className="mt-2 text-white/70">
  {analyzed
    ? `Analysis generated for ${fileName}`
    : "Example insights generated by our AI"}
</p>


            {/* Cards */}
            <div className="grid grid-cols-2 gap-4 mt-8">

              <div className="bg-white/10 rounded-2xl p-5">
                <p className="text-white/70">
                  Skill Match
                </p>
                <h3 className="text-4xl font-bold mt-2">
                    {analyzed ? "91%" : "85%"}
                </h3>
              </div>

              <div className="bg-white/10 rounded-2xl p-5">
                <p className="text-white/70">
                  Interview Ready
                </p>
                <h3 className="text-4xl font-bold mt-2">
                    {analyzed ? "88%" : "72%"}
                </h3>
              </div>

            </div>

            {/* Skills */}
            <div className="mt-10 space-y-6">

              <div>
                <div className="flex justify-between mb-2">
                  <span>React</span>
                  <span>92%</span>
                </div>

                <div className="h-3 bg-white/20 rounded-full">
                  <div className="h-3 w-[92%] bg-yellow-300 rounded-full"></div>
                </div>
              </div>

              <div>
                <div className="flex justify-between mb-2">
                  <span>Node.js</span>
                  <span>75%</span>
                </div>

                <div className="h-3 bg-white/20 rounded-full">
                  <div className="h-3 w-[75%] bg-blue-300 rounded-full"></div>
                </div>
              </div>

              <div>
                <div className="flex justify-between mb-2">
                  <span>System Design</span>
                  <span>48%</span>
                </div>

                <div className="h-3 bg-white/20 rounded-full">
                  <div className="h-3 w-[48%] bg-red-300 rounded-full"></div>
                </div>
              </div>

            </div>

            {/* Missing Skills */}
            <div
  className={`mt-10 rounded-3xl p-6 ${
    analyzed
      ? "bg-green-200 text-[#171C4A]"
      : "bg-yellow-200 text-[#171C4A]"
  }`}
>
              <p className="text-sm font-medium">
                Missing Skills
              </p>
<div className="mt-2 flex flex-wrap gap-2">

  {analyzed ? (
    <>
      <span className="px-3 py-1 bg-white rounded-full">
        Kubernetes
      </span>

      <span className="px-3 py-1 bg-white rounded-full">
        Microservices
      </span>

      <span className="px-3 py-1 bg-white rounded-full">
        CI/CD
      </span>
    </>
  ) : (
    <>
      <span className="px-3 py-1 bg-white rounded-full">
        Docker
      </span>

      <span className="px-3 py-1 bg-white rounded-full">
        AWS
      </span>

      <span className="px-3 py-1 bg-white rounded-full">
        AI/ML
      </span>
    </>
  )}

</div>
            </div>

          </div>
        </div>
      </div>
      {showPopup && (
  <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50">

    <div className="bg-white rounded-[32px] p-10 max-w-md w-full mx-4 shadow-2xl animate-[bounce_1s_ease-in-out]">

      <div className="text-center">

        <div className="text-7xl mb-4">
          🎉
        </div>

        <h2 className="text-3xl font-bold text-[#171C4A]">
          Analysis Complete!
        </h2>

        <p className="mt-4 text-gray-500">
          Your resume has been analyzed successfully.
        </p>

        <div className="mt-6 bg-[#F8F6E8] rounded-2xl p-5">

          <h3 className="font-bold text-[#171C4A] text-lg">
            Unlock More Features
          </h3>

          <div className="mt-4 space-y-3 text-left">

            <div className="flex items-center gap-3">
              <span>🚀</span>
              <span>Personalized Learning Roadmaps</span>
            </div>

            <div className="flex items-center gap-3">
              <span>🐙</span>
              <span>GitHub Skill Analysis</span>
            </div>

            <div className="flex items-center gap-3">
              <span>🏆</span>
              <span>XP & Progress Tracking</span>
            </div>

            <div className="flex items-center gap-3">
              <span>🎯</span>
              <span>AI Mock Interviews</span>
            </div>

            <div className="flex items-center gap-3">
              <span>📚</span>
              <span>Daily Learning Missions</span>
            </div>

          </div>

        </div>

<div className="mt-8 space-y-3">
  <button

  onClick={() => {
    setShowPopup(false);
    setShowSignup(true);
  }}
  className="w-full py-4 rounded-2xl bg-[#171C4A] text-white font-bold"
>
  Create Free Account →
</button>

        <button
          onClick={onLogin}
          className="w-full mt-8 py-4 rounded-2xl bg-[#171C4A] text-white font-bold text-lg hover:bg-[#0f1438]"
        >
          Sign In To Continue →
        </button>
</div>
       

      </div>

    </div>

  </div>
)}

{showSignup && (
  <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50">

    <div className="bg-white rounded-[36px] p-8 w-full max-w-md shadow-2xl">

      <div className="text-center">

        <div className="text-6xl mb-4">
          🚀
        </div>

        <h2 className="text-3xl font-bold text-[#171C4A]">
          Create Your Account
        </h2>

        <p className="text-gray-500 mt-2">
          Unlock personalized roadmaps, GitHub analysis,
          mock interviews and progress tracking.
        </p>

      </div>

      <div className="mt-8 space-y-4">

        <input
          type="text"
          placeholder="Full Name"
          className="w-full border border-gray-300 rounded-2xl px-4 py-3"
        />

        <input
          type="email"
          placeholder="Email Address"
          className="w-full border border-gray-300 rounded-2xl px-4 py-3"
        />

        <input
          type="password"
          placeholder="Create Password"
          className="w-full border border-gray-300 rounded-2xl px-4 py-3"
        />

        <button
          onClick={() => {
            onDashboard(); 
          }}
          className="w-full py-4 rounded-2xl bg-[#171C4A] text-white font-bold"
        >
          Create Account →
        </button>

      </div>

      <div className="flex items-center my-6">
        <div className="flex-1 h-px bg-gray-300"></div>
        <span className="px-3 text-gray-400">OR</span>
        <div className="flex-1 h-px bg-gray-300"></div>
      </div>

      <button className="w-full border rounded-2xl py-3 flex items-center justify-center gap-3">

        <img
          src="https://www.svgrepo.com/show/475656/google-color.svg"
          alt="Google"
          className="w-5 h-5"
        />

        Continue with Google

      </button>

      <p className="text-center mt-6 text-gray-500">

        Already have an account?

        <span
          className="font-semibold text-[#171C4A] ml-2 cursor-pointer"
          onClick={() => {
            setShowSignup(false);
            onLogin();
          }}
        >
          Sign In
        </span>

      </p>

    </div>

  </div>
)} 
    </section>
  );
}

