/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeAnalysisCoverRouteImport } from './routes/resume-analysis-cover'
import { Route as ResumeAnalysisRouteImport } from './routes/resume-analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PublicResumeDetailsRouteImport } from './routes/_public/ResumeDetails'
import { Route as AuthenticatedSkillGapDashboardRouteImport } from './routes/_authenticated/SkillGapDashboard'
import { Route as AuthenticatedRoadmapVisualizationRouteImport } from './routes/_authenticated/RoadmapVisualization'
import { Route as AuthenticatedLearningTimelineRouteImport } from './routes/_authenticated/LearningTimeline'
import { Route as AuthCallbackGoogleRouteImport } from './routes/auth/callback/google'
import { Route as AuthCallbackGithubRouteImport } from './routes/auth/callback/github'

const ResumeAnalysisCoverRoute = ResumeAnalysisCoverRouteImport.update({
  id: '/resume-analysis-cover',
  path: '/resume-analysis-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalysisRoute = ResumeAnalysisRouteImport.update({
  id: '/resume-analysis',
  path: '/resume-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicResumeDetailsRoute = PublicResumeDetailsRouteImport.update({
  id: '/ResumeDetails',
  path: '/ResumeDetails',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedSkillGapDashboardRoute =
  AuthenticatedSkillGapDashboardRouteImport.update({
    id: '/SkillGapDashboard',
    path: '/SkillGapDashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoadmapVisualizationRoute =
  AuthenticatedRoadmapVisualizationRouteImport.update({
    id: '/RoadmapVisualization',
    path: '/RoadmapVisualization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearningTimelineRoute =
  AuthenticatedLearningTimelineRouteImport.update({
    id: '/LearningTimeline',
    path: '/LearningTimeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthCallbackGoogleRoute = AuthCallbackGoogleRouteImport.update({
  id: '/auth/callback/google',
  path: '/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackGithubRoute = AuthCallbackGithubRouteImport.update({
  id: '/auth/callback/github',
  path: '/auth/callback/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/resume-analysis': typeof ResumeAnalysisRoute
  '/resume-analysis-cover': typeof ResumeAnalysisCoverRoute
  '/LearningTimeline': typeof AuthenticatedLearningTimelineRoute
  '/RoadmapVisualization': typeof AuthenticatedRoadmapVisualizationRoute
  '/SkillGapDashboard': typeof AuthenticatedSkillGapDashboardRoute
  '/ResumeDetails': typeof PublicResumeDetailsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/callback/github': typeof AuthCallbackGithubRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/resume-analysis': typeof ResumeAnalysisRoute
  '/resume-analysis-cover': typeof ResumeAnalysisCoverRoute
  '/LearningTimeline': typeof AuthenticatedLearningTimelineRoute
  '/RoadmapVisualization': typeof AuthenticatedRoadmapVisualizationRoute
  '/SkillGapDashboard': typeof AuthenticatedSkillGapDashboardRoute
  '/ResumeDetails': typeof PublicResumeDetailsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/callback/github': typeof AuthCallbackGithubRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/resume-analysis': typeof ResumeAnalysisRoute
  '/resume-analysis-cover': typeof ResumeAnalysisCoverRoute
  '/_authenticated/LearningTimeline': typeof AuthenticatedLearningTimelineRoute
  '/_authenticated/RoadmapVisualization': typeof AuthenticatedRoadmapVisualizationRoute
  '/_authenticated/SkillGapDashboard': typeof AuthenticatedSkillGapDashboardRoute
  '/_public/ResumeDetails': typeof PublicResumeDetailsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/callback/github': typeof AuthCallbackGithubRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/resume-analysis'
    | '/resume-analysis-cover'
    | '/LearningTimeline'
    | '/RoadmapVisualization'
    | '/SkillGapDashboard'
    | '/ResumeDetails'
    | '/auth/login'
    | '/auth/callback/github'
    | '/auth/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/resume-analysis'
    | '/resume-analysis-cover'
    | '/LearningTimeline'
    | '/RoadmapVisualization'
    | '/SkillGapDashboard'
    | '/ResumeDetails'
    | '/auth/login'
    | '/auth/callback/github'
    | '/auth/callback/google'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/dashboard'
    | '/resume-analysis'
    | '/resume-analysis-cover'
    | '/_authenticated/LearningTimeline'
    | '/_authenticated/RoadmapVisualization'
    | '/_authenticated/SkillGapDashboard'
    | '/_public/ResumeDetails'
    | '/auth/login'
    | '/auth/callback/github'
    | '/auth/callback/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ResumeAnalysisRoute: typeof ResumeAnalysisRoute
  ResumeAnalysisCoverRoute: typeof ResumeAnalysisCoverRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthCallbackGithubRoute: typeof AuthCallbackGithubRoute
  AuthCallbackGoogleRoute: typeof AuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume-analysis-cover': {
      id: '/resume-analysis-cover'
      path: '/resume-analysis-cover'
      fullPath: '/resume-analysis-cover'
      preLoaderRoute: typeof ResumeAnalysisCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analysis': {
      id: '/resume-analysis'
      path: '/resume-analysis'
      fullPath: '/resume-analysis'
      preLoaderRoute: typeof ResumeAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/ResumeDetails': {
      id: '/_public/ResumeDetails'
      path: '/ResumeDetails'
      fullPath: '/ResumeDetails'
      preLoaderRoute: typeof PublicResumeDetailsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/SkillGapDashboard': {
      id: '/_authenticated/SkillGapDashboard'
      path: '/SkillGapDashboard'
      fullPath: '/SkillGapDashboard'
      preLoaderRoute: typeof AuthenticatedSkillGapDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/RoadmapVisualization': {
      id: '/_authenticated/RoadmapVisualization'
      path: '/RoadmapVisualization'
      fullPath: '/RoadmapVisualization'
      preLoaderRoute: typeof AuthenticatedRoadmapVisualizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/LearningTimeline': {
      id: '/_authenticated/LearningTimeline'
      path: '/LearningTimeline'
      fullPath: '/LearningTimeline'
      preLoaderRoute: typeof AuthenticatedLearningTimelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback/google': {
      id: '/auth/callback/google'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google'
      preLoaderRoute: typeof AuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/github': {
      id: '/auth/callback/github'
      path: '/auth/callback/github'
      fullPath: '/auth/callback/github'
      preLoaderRoute: typeof AuthCallbackGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLearningTimelineRoute: typeof AuthenticatedLearningTimelineRoute
  AuthenticatedRoadmapVisualizationRoute: typeof AuthenticatedRoadmapVisualizationRoute
  AuthenticatedSkillGapDashboardRoute: typeof AuthenticatedSkillGapDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLearningTimelineRoute: AuthenticatedLearningTimelineRoute,
  AuthenticatedRoadmapVisualizationRoute:
    AuthenticatedRoadmapVisualizationRoute,
  AuthenticatedSkillGapDashboardRoute: AuthenticatedSkillGapDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicResumeDetailsRoute: typeof PublicResumeDetailsRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicResumeDetailsRoute: PublicResumeDetailsRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ResumeAnalysisRoute: ResumeAnalysisRoute,
  ResumeAnalysisCoverRoute: ResumeAnalysisCoverRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthCallbackGithubRoute: AuthCallbackGithubRoute,
  AuthCallbackGoogleRoute: AuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
